### ISSUE TITLE
inline HTMLBlock Content not supported?

### ISSUE THREAD

**Issue by LiYanan2004** [apple/swift-markdown#69] opened 2022-08-13 10:36 UTC
I can only get the text of the **HTML Tag**, but not the content. Is this a bug?

<img width="459" alt="截屏2022-08-13 18 34 44" src="https://user-images.githubusercontent.com/37542129/184479941-e4dfe9a3-e5d9-468b-91a7-4c32c07ddc52.png">

**Comment by Kyle-Ye** [comment] 2022-09-25 07:53
Sorry,I'm a little vague about your question.

Could provide a more descriptive infomation?

eg. `your string/source input`, `minimal code snippest to reproduce your problem`, `expected output` and `actual output`.

Looks like we can both get the tag(eg. "kbd") and the content(eg. "Ctrl").

**Comment by LiYanan2004** [comment] 2023-01-27 07:06
Maybe it's my misunderstanding of this inline block. What I expected is like below:

Document
└ Paragraph
├─ InlineHTML "<kbd>Ctrl</kbd>"
├─ Text "+"
├─ InlineHTML "<kbd>Alt</kbd>"
├─ Text "+"
├─ InlineHTML "<kbd>Del</kbd>"

**Comment by QuietMisdreavus** [comment] 2023-01-30 16:41
CommonMark (and GitHub-Flavored Markdown, which we use a fork of) doesn't include tag *contents* as part of an Inline HTML span, just the tag or closing tag: https://github.github.com/gfm/#raw-html

**Closed** 2023-03-20 05:06 UTC
