### ISSUE TITLE
MarkdownText powered by swift-markdown

### ISSUE THREAD

**Issue by shaps80** [apple/swift-markdown#77] opened 2022-09-16 19:48 UTC
Just wanted to say thanks for open sourcing this. 👏

This enabled me to build a really cool open source package [MarkdownText](https://github.com/shaps80/MarkdownText) that provides similar support to Apples iOS 15+ Text markdown support.

But it works back to iOS 13+ and macOS 11+ and even includes a lot of styling APIs.

Bit of a shameless plug but wanted to mention it here in case it's useful to anyone else.

- Headings
- Paragraphs
- Quotes
- Inline formatting
  - Strong/Bold
  - Emphasis/Italic
  - Strikethrough
  - Code
  - Links (non interactive only)
- Lists
  - Ordered
  - Unordered
  - Checklist (GitHub style)
- Thematic Breaks
- Code Blocks
- Images

> A full backport of AsyncImage is included to make image support simple and performant.

Since it's pure SwiftUI you can even easily animate content which is a nice plus.

**Comment by shaps80** [comment] 2022-09-16 19:49
On a side note I noticed the library doesn't currently support ordered list indexes that don't start from 1. Would be amazing if this could be added 👍👍

**Comment by QuietMisdreavus** [comment] 2022-09-16 19:53
"Ordered lists that don't start from 1" is being added in https://github.com/apple/swift-markdown/pull/22 ✌️

Thanks for the shoutout!

**Comment by QuietMisdreavus** [comment] 2022-09-16 19:56
Is there another bug report you wanted to include? You might get a better reach for your project if you post about it in the [Swift Forums](https://forums.swift.org/c/development/swift-docc/80) instead of a GitHub issue.

**Comment by shaps80** [comment] 2022-09-17 12:57
Good shout thanks, will do!

**Comment by QuietMisdreavus** [comment] 2022-11-15 17:12
I'm going to close this since it's not a bug report or feature request. If you have something you'd like to see in Swift-Markdown, definitely let us know!

**Closed by QuietMisdreavus** 2022-11-15 17:12 UTC
